name: TV Management
description: |
  This is everything to do with TV and Media catalog management
version: 1
category: Applications
maintainer: Sean
license: Apache 2.0
projectURL: https://www.muzik.ca/
